# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "619efa429740598f93a2ef8f8d711cca"
name = "SmartBill"
handle = "smartbill-1"
application_url = "https://smart-bill-self.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "creatorsstore254.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_inventory,read_inventory"

[auth]
redirect_urls = [
  "https://smart-bill-self.vercel.app/auth/callback",
  "https://smart-bill-self.vercel.app/auth/shopify/callback",
  "https://smart-bill-self.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-10"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/compliance"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[pos]
embedded = false
