BEGIN;
ALTER TABLE "Invoice" ADD COLUMN "landedCostMethod" TEXT NOT NULL DEFAULT 'NONE';

ALTER TABLE "Invoice" ADD COLUMN "landedCostUpdatedAt" TIMESTAMP(3);
ALTER TABLE "InvoiceItem" ADD COLUMN "category" TEXT NOT NULL DEFAULT 'PRODUCT';
ALTER TABLE "InvoiceItem" ADD COLUMN "manualCharge" DOUBLE PRECISION;
ALTER TABLE "CostChange" ADD COLUMN "landedCostPerUnit" DOUBLE PRECISION;
ALTER TABLE "CostChange" ADD COLUMN "allocation" JSONB;
COMMIT;